/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setResizable(false);
        setTitle("Acceso al Sistema");
        setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/imagenes/fondo.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lblWallpaper.getWidth(), lblWallpaper.getHeight(), Image.SCALE_SMOOTH));
        lblWallpaper.setIcon(icono);
        this.repaint();

        ImageIcon waImageIcon = new ImageIcon("src/imagenes/umg.png");
        Icon icono_logo = new ImageIcon(waImageIcon.getImage().getScaledInstance(lblumg.getWidth(), lblumg.getHeight(), Image.SCALE_SMOOTH));
        lblumg.setIcon(icono_logo);
        this.repaint();

        ImageIcon iconSalir = new ImageIcon(getClass().getResource("/imagenes/exit.png"));
        Image imgSalir = iconSalir.getImage().getScaledInstance(btnExit.getWidth(), btnExit.getHeight(), Image.SCALE_SMOOTH);
        btnExit.setIcon(new ImageIcon(imgSalir));
        btnExit.setContentAreaFilled(false);
        btnExit.setBorderPainted(false);
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(false);

        ImageIcon infor = new ImageIcon(getClass().getResource("/imagenes/info.png"));
        Image info = infor.getImage().getScaledInstance(btnInfo.getWidth(), btnInfo.getHeight(), Image.SCALE_SMOOTH);
        btnInfo.setIcon(new ImageIcon(info));
        btnInfo.setContentAreaFilled(false);
        btnInfo.setBorderPainted(false);
        btnInfo.setFocusPainted(false);
        btnInfo.setOpaque(false);

    }

    @Override
    public Image getIconImage() {
        Image retValue;
        retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        lblumg = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblFooter = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();
        lblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresar.setBackground(new java.awt.Color(102, 102, 102));
        btnIngresar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Aceptar");
        btnIngresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 130, 50));

        lblumg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblumg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 240, 230));

        jTextFieldNombre.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 240, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Ingresa tú Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        btnExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 50, 50));

        lblFooter.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        lblFooter.setText("Grupo #1");
        getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        btnInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));
        getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String nombre = jTextFieldNombre.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa tu nombre.", "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (nombre.contains(" ")) {
            JOptionPane.showMessageDialog(this, "Ingresa solo tu primer nombre (sin espacios crack).", "Nombre inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ]+")) {
            JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras.", "Nombre inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Principal ventanaPrincipal = new Principal(nombre);
        ventanaPrincipal.setVisible(true);
        this.dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);    }//GEN-LAST:event_btnExitActionPerformed
    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        String mensaje = """
            Proyecto – Sistemas Operativos
            Algoritmo Prioridad
            Grupo #M.M
            Java Swing ©
            """;

        // Muestra el mensaje centrado en una ventana de información
        JOptionPane.showMessageDialog(
                this,
                "<html><center>" + mensaje.replaceAll("\n", "<br>") + "</center></html>",
                "Información del Proyecto",
                JOptionPane.INFORMATION_MESSAGE
    );    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JLabel lblumg;
    // End of variables declaration//GEN-END:variables
}
